ALTER FUNCTION public.add_stock(TEXT,TEXT,INTEGER,TEXT,UUID,UUID,DATE) SECURITY INVOKER;
ALTER FUNCTION public.create_trade(UUID,TEXT,DATE,TEXT,JSONB) SECURITY INVOKER;
ALTER FUNCTION public.sell_stock(UUID,INTEGER,NUMERIC,NUMERIC,NUMERIC,DATE,TEXT) SECURITY INVOKER;
ALTER FUNCTION public.seed_demo_data() SECURITY INVOKER;

REVOKE ALL ON FUNCTION public.add_stock(TEXT,TEXT,INTEGER,TEXT,UUID,UUID,DATE) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_trade(UUID,TEXT,DATE,TEXT,JSONB) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.sell_stock(UUID,INTEGER,NUMERIC,NUMERIC,NUMERIC,DATE,TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.seed_demo_data() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.touch_updated_at() FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.add_stock(TEXT,TEXT,INTEGER,TEXT,UUID,UUID,DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_trade(UUID,TEXT,DATE,TEXT,JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sell_stock(UUID,INTEGER,NUMERIC,NUMERIC,NUMERIC,DATE,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.seed_demo_data() TO authenticated;